--truncate table users CASCADE;
--truncate table lists CASCADE;
--
--truncate table global_roles CASCADE;
--truncate table project_users CASCADE;
--truncate table items CASCADE;


drop table IF EXISTS users CASCADE;
drop table IF EXISTS global_roles CASCADE;
drop table IF EXISTS project_users CASCADE;
drop table IF EXISTS lists CASCADE;
drop table IF EXISTS items CASCADE;
drop table IF EXISTS project_roles   CASCADE;
drop table IF EXISTS projects   CASCADE;
drop table IF EXISTS steps   CASCADE;
drop table IF EXISTS locks  CASCADE;
DROP TYPE IF EXISTS public.globalroletype;
DROP TYPE IF EXISTS public.projectroletype;
--
-- PostgreSQL database dump
--

\set VERBOSITY terse

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: globalroletype; Type: TYPE; Schema: public; Owner: dev
--

CREATE TYPE public.globalroletype AS ENUM (
    'CLIENT',
    'WORKER'
);


ALTER TYPE public.globalroletype OWNER TO dev;

--
-- Name: projectroletype; Type: TYPE; Schema: public; Owner: dev
--

CREATE TYPE public.projectroletype AS ENUM (
    'CREATOR',
    'USER'
);


ALTER TYPE public.projectroletype OWNER TO dev;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.users (
    external_id character varying NOT NULL,
    internal_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

ALTER TABLE public.users OWNER TO dev;

--
-- Name: global_roles; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.global_roles (
    id integer NOT NULL,
    user_id integer NOT NULL,
    role_type public.globalroletype NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.global_roles OWNER TO dev;

--
-- Name: global_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.global_roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.global_roles_id_seq OWNER TO dev;

--
-- Name: global_roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.global_roles_id_seq OWNED BY public.global_roles.id;


--
-- Name: items; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.items (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    category character varying,
    quantity integer,
    price double precision,
    list_id integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    item_link character varying,
    item_photo_link character varying,
    delivery_price double precision,
    delivery_period integer,
    store_address character varying,
    store_distance double precision,
    approved integer,
    bought integer,
    delivered integer
);


ALTER TABLE public.items OWNER TO dev;

--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.items_id_seq OWNER TO dev;

--
-- Name: items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.items_id_seq OWNED BY public.items.id;


--
-- Name: project_users; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.project_users (
    id integer NOT NULL,
    user_id integer NOT NULL,
    project_id integer NOT NULL,
    role_type public.projectroletype NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.project_users OWNER TO dev;

--
-- Name: project_users_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.project_users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.project_users_id_seq OWNER TO dev;

--
-- Name: project_users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.project_users_id_seq OWNED BY public.project_users.id;


--
-- Name: lists; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.lists (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    destination_address character varying,
    project_id integer NOT NULL,
    step_id integer NOT NULL UNIQUE
);


ALTER TABLE public.lists OWNER TO dev;

--
-- Name: lists_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.lists_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.lists_id_seq OWNER TO dev;

--
-- Name: lists_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.lists_id_seq OWNED BY public.lists.id;


--
-- Name: locks; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.locks (
    id integer NOT NULL,
    list_id integer NOT NULL,
    holder_id integer NOT NULL,
--    acquired_at timestamp with time zone DEFAULT now() NOT NULL,
    acquired_at timestamp without time zone DEFAULT now() NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.locks OWNER TO dev;

--
-- Name: locks_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.locks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.locks_id_seq OWNER TO dev;

--
-- Name: locks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.locks_id_seq OWNED BY public.locks.id;

--
-- Name: project_roles; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.project_roles (
    id integer NOT NULL,
    role_type public.projectroletype NOT NULL,
    description character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.project_roles OWNER TO dev;

--
-- Name: project_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.project_roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.project_roles_id_seq OWNER TO dev;

--
-- Name: project_roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.project_roles_id_seq OWNED BY public.project_roles.id;

--
-- Name: projects; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.projects (
    id integer NOT NULL,
    name character varying NOT NULL,
    place_description character varying,
    planned_start_date timestamp with time zone,
    planned_end_date timestamp with time zone,
    actual_start_date timestamp with time zone,
    actual_end_date timestamp with time zone,
    total_materials_price double precision,
    total_workers_price double precision,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

ALTER TABLE public.projects OWNER TO dev;

--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.projects_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.projects_id_seq OWNER TO dev;

ALTER SEQUENCE public.projects_id_seq OWNED BY public.projects.id;

--
-- Name: steps; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.steps (
    id integer NOT NULL,
    name character varying NOT NULL,
    planned_start_date timestamp with time zone,
    planned_end_date timestamp with time zone,
    actual_start_date timestamp with time zone,
    actual_end_date timestamp with time zone,
    materials_price double precision,
    workers_price double precision,
    project_id integer NOT NULL,
    parent_step_id integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);

ALTER TABLE public.steps OWNER TO dev;

--
-- Name: steps_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.steps_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.steps_id_seq OWNER TO dev;

ALTER SEQUENCE public.steps_id_seq OWNED BY public.steps.id;


--
-- Name: global_roles id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.global_roles ALTER COLUMN id SET DEFAULT nextval('public.global_roles_id_seq'::regclass);


--
-- Name: items id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.items ALTER COLUMN id SET DEFAULT nextval('public.items_id_seq'::regclass);


--
-- Name: project_users id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_users ALTER COLUMN id SET DEFAULT nextval('public.project_users_id_seq'::regclass);


--
-- Name: lists id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.lists ALTER COLUMN id SET DEFAULT nextval('public.lists_id_seq'::regclass);


--
-- Name: locks id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.locks ALTER COLUMN id SET DEFAULT nextval('public.locks_id_seq'::regclass);

--
-- Name: project_roles id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_roles ALTER COLUMN id SET DEFAULT nextval('public.project_roles_id_seq'::regclass);

--
-- Name: projects id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.projects ALTER COLUMN id SET DEFAULT nextval('public.projects_id_seq'::regclass);

--
-- Name: steps id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.steps ALTER COLUMN id SET DEFAULT nextval('public.steps_id_seq'::regclass);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (internal_id);

--
-- Name: users users_external_id_key; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_external_id_key UNIQUE (external_id);

--
-- Name: global_roles global_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.global_roles
    ADD CONSTRAINT global_roles_pkey PRIMARY KEY (id);

--
-- Name: global_roles global_roles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.global_roles
    ADD CONSTRAINT global_roles_user_id_key UNIQUE (user_id);

--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: project_users project_users_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT project_users_pkey PRIMARY KEY (id);


--
-- Name: lists lists_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.lists
    ADD CONSTRAINT lists_pkey PRIMARY KEY (id);


--
-- Name: locks locks_list_id_key; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.locks
    ADD CONSTRAINT locks_list_id_key UNIQUE (list_id);


--
-- Name: locks locks_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.locks
    ADD CONSTRAINT locks_pkey PRIMARY KEY (id);


--
-- Name: project_users unique_user_project; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT unique_user_project UNIQUE (user_id, project_id);

--
-- Name: project_roles project_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_roles
    ADD CONSTRAINT project_roles_pkey PRIMARY KEY (id);

--
-- Name: project_roles project_roles_role_type_key; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_roles
    ADD CONSTRAINT project_roles_role_type_key UNIQUE (role_type);

--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

--
-- Name: steps steps_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_pkey PRIMARY KEY (id);

--
-- Name: ix_users_external_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE INDEX ix_users_external_id ON public.users USING btree (external_id);

--
-- Name: ix_users_internal_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE UNIQUE INDEX ix_users_internal_id ON public.users USING btree (internal_id);

--
-- Name: ix_project_users_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE INDEX ix_project_users_id ON public.project_users USING btree (id);


--
-- Name: ix_locks_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE INDEX ix_locks_id ON public.locks USING btree (id);

--
-- Name: ix_project_roles_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE INDEX ix_project_roles_id ON public.project_roles USING btree (id);

--
-- Name: ix_projects_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE INDEX ix_projects_id ON public.projects USING btree (id);

--
-- Name: ix_steps_id; Type: INDEX; Schema: public; Owner: dev
--

CREATE INDEX ix_steps_id ON public.steps USING btree (id);

--
-- Name: global_roles global_roles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.global_roles
    ADD CONSTRAINT global_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(internal_id);

--
-- Name: items items_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lists(id);


--
-- Name: project_users project_users_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT project_users_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id);


--
-- Name: project_users project_users_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT project_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(internal_id);


--
-- Name: locks locks_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.locks
    ADD CONSTRAINT locks_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lists(id);


--
-- Name: locks locks_holder_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.locks
    ADD CONSTRAINT locks_holder_id_fkey FOREIGN KEY (holder_id) REFERENCES public.users(internal_id);

--
-- Name: steps steps_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id);

--
-- Name: steps steps_parent_step_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.steps
    ADD CONSTRAINT steps_parent_step_id_fkey FOREIGN KEY (parent_step_id) REFERENCES public.steps(id);

--
-- Name: lists lists_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.lists
    ADD CONSTRAINT lists_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id);

--
-- Name: lists lists_step_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.lists
    ADD CONSTRAINT lists_step_id_fkey FOREIGN KEY (step_id) REFERENCES public.steps(id);

--
-- Data for Name: project_roles; Type: TABLE DATA; Schema: public; Owner: dev
--

INSERT INTO public.project_roles (role_type, description) VALUES ('CREATOR', 'Creator of a project');
INSERT INTO public.project_roles (role_type, description) VALUES ('USER', 'User of a project');

--
-- PostgreSQL database dump complete
--

\set VERBOSITY default
